[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "tic_tac_taco_pizza"
author = "Mariatta Wijaya"
author-email = "mariatta.wijaya@gmail.com"
maintainer = "Mariatta Wijaya"
maintainer-email = "mariatta.wijaya@gmail.com"
home-page = "https://github.com/Mariatta/tic_tac_taco_pizza"
requires = ["click~=6.7"]
description-file = "readme.rst"
classifiers = ["Programming Language :: Python :: 3.6", "Intended Audience :: Developers", "License :: OSI Approved :: Apache Software License"]
requires-python = ">=3.6"


[tool.flit.scripts]
tic_tac_taco_pizza = "tic_tac_taco_pizza:tic_tac_taco_pizza"
